#!/bin/bash

# Deps:
# 	curl


get_weather()
{
  curl -s v2.wttr.in | grep -e "Weather" | sed -n 2p | sed s/Weather://g | sed 's/,//g' | sed 's/+//g' | sed 's/°C.*/°C/' | sed 's/.*m//' > weather.buffer && echo $(date '+%H') >> weather.buffer
}

check_weather()
{
  if [ -f ./weather.buffer ]; then
    WHOUR=$(tail -n1 weather.buffer)
    if [ $(date '+%H') -ne $WHOUR ]; then
      get_weather
    fi
  else
    get_weather
  fi
  head -n1 ./weather.buffer | awk ' {k=" "}; {for(i=1;i<=NF;i++) {k=k" "$i;}; print k}'
}

# if [ $(( 10#$(date '+%S') % 30 )) -eq 0 ]; then
# 	get_weather
# fi

# check_weather
